defaults:
    - base_mixture
    
# this needs to be specified manually
experiment: RIME

# RIME specific parameters
threshold_beta_init: 2.0
threshold_beta_min: 0.1

# hydra configuration
hydra:
    run:
        dir: ./exp_rime_mixture/${env}/seed${seed}/max_feedback${max_feedback}_n${reward_batch}_l${segment}_g${teacher_gamma}_b${teacher_beta}_m${teacher_eps_mistake}_s${teacher_eps_skip}_e${teacher_eps_equal}
